### ISSUE TITLE
Implement four arithmetic operations

### ISSUE THREAD

**Issue by yjh0816** [yjh0816/four-arithmetic-operations#1]
### Description
Implement four arithmetic operations

### Tasks
- [ ] Implement Add function
- [ ] Implement Subtract function
- [ ] Implement Divide function
- [ ] Implement Multiply function
