### ISSUE TITLE
Implement Subtract function

### ISSUE THREAD

**Issue by Research-Mini** [yjh0816/four-arithmetic-operations#2]
### Description
Implement Subtract tunction for four arithmetic operations

### To-Do

- [ ] make two variable A, B
- [ ] input two int type argument from user
- [ ] save first argument at A
- [ ] save second argument at B
- [ ] make new variable Answer
- [ ] calculate A-B
- [ ] save A-B to Answer
- [ ] print Answer
